### ISSUE TITLE
One unit test fails on 64bits simulator

### ISSUE THREAD

**Issue by ignazioc** [plu/VCRURLSession#1]
This spec:
```
it("stores userInfo") {
  expect(result["userInfo"] as? String).to(equal(encodedUserInfo))
}
```
when the tests are ran on the iPhone6s+ and iPad Pro. Both are 64bits, so I believe that this is can be the problem.

Any prize for the 1st issue? :)

**Comment by plu** [comment]
Thank you for finding this :). The prize is you own the issue with the number "1" :).
